version: "3"
services:
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    restart: always
    environment:
      TZ: "America/Los_Angeles"
      PUID: "1001"
      PGID: "0"
    ports:
      - "8081:8080"
      - "9090:9090"
    volumes:
      - "${LAB_STORAGE:?err}/config/sabnzbd:/config"
      - "${LAB_STORAGE:?err}/download/sabnzbd/complete:/downloads"
      - "${LAB_STORAGE:?err}/download/sabnzbd/downloading:/incomplete-downloads"
  radarr:
    depends_on:
      - sabnzbd
    image: linuxserver/radarr:latest
    restart: always
    environment:
      TZ: "America/Los_Angeles"
      PUID: "1001"
      PGID: "0"
    ports:
      - "7878:7878"
    volumes:
      - "${LAB_STORAGE:?err}/config/radarr:/config"
      - "${LAB_STORAGE:?err}/plex/movies:/movies"
      - "${LAB_STORAGE:?err}/download/sabnzbd/complete/movies:/downloads"
  sonarr:
    depends_on:
      - sabnzbd
    image: linuxserver/sonarr:latest
    restart: always
    environment:
      TZ: "America/Los_Angeles"
      PUID: "1001"
      PGID: "0"
    ports:
      - "8989:8989"
    volumes:
      - "${LAB_STORAGE:?err}/config/sonarr:/config"
      - "${LAB_STORAGE:?err}/plex/tv:/tv"
      - "${LAB_STORAGE:?err}/download/sabnzbd/complete:/downloads"
  plex:
    image: linuxserver/plex:latest
    restart: always
    environment:
      TZ: "America/Los_Angeles"
      PUID: "1001"
      PGID: "0"
      VERSION: latest
    network_mode: "host"
    volumes:
      - "${LAB_STORAGE:?err}/config/plex:/config"
      - "${LAB_STORAGE:?err}/plex/tv:/data/tvshows"
      - "${LAB_STORAGE:?err}/plex/movies:/data/movies"
      - "${LAB_STORAGE:?err}/plex/music:/data/music"
  openvpn:
    image: kylemanna/openvpn:latest
    restart: always
    # network_mode: "host"
    ports:
      - "1194:1194/udp"
    environment:
      TZ: "America/Los_Angeles"
    cap_add:
      - "NET_ADMIN"
    volumes:
      - "${LAB_STORAGE:?err}/config/openvpn:/etc/openvpn"
  appdaemon:
    restart: always
    depends_on:
      - hass
    image: acockburn/appdaemon:latest
    environment:
      TZ: "America/Los_Angeles"
    ports:
      - "5050:5050"
    volumes:
      - "${LAB_STORAGE:?err}/config/homeassistant:/conf"
      - "/etc/localtime:/etc/localtime:ro"
  hass:
    image: homeassistant/home-assistant:latest
    restart: always
    network_mode: "host"
    environment:
      TZ: "America/Los_Angeles"
      PUID: "1001"
      PGID: "0"
    volumes:
      - "${LAB_STORAGE:?err}/config/homeassistant:/config"
      - "/etc/localtime:/etc/localtime:ro"
  unifi-video:
    image: pducharme/unifi-video-controller:latest
    restart: always
    network_mode: "host"
    environment:
      TZ: "America/Los_Angeles"
      PUID: "1001"
      PGID: "0"
      DEBUG: "1"
    cap_add:
      - "SYS_ADMIN"
      - "DAC_READ_SEARCH"
    security_opt:
      - apparmor:unconfined
    volumes:
      - "${LAB_STORAGE:?err}/config/unifi-video:/var/lib/unifi-video"
      #- "${LAB_STORAGE:?err}/config/unifi-video/video:/usr/lib/unifi-video/data/video"
  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
    restart: unless-stopped
    environment:
      ServerIP: 104.156.103.41
      TZ: "America/Los_Angeles"
      WEBPASSWORD: pihole
      VIRTUAL_HOST: 'xenial'
      PUID: "1001"
      PGID: "0"
    volumes:
      - "${LAB_STORAGE:?err}/config/pihole:/etc/pihole"
      - "${LAB_STORAGE:?err}/config/pihole/pihole_dnsmasq:/etc/dnsmasq.d"
  # plexrequests:
  #   depends_on:
  #     - plex
  #   image: linuxserver/plexrequests:latest
  #   restart: always
  #   environment:
  #     TZ: "America/Los_Angeles"
  #     PUID: "1001"
  #     PGID: "0"
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - "${LAB_STORAGE:?err}/config/plexrequests:/config"
  #     - "/etc/localtime:/etc/localtime:ro"
  # musicbrainz:
  #   depends_on:
  #     - plex
  #   image: linuxserver/musicbrainz:latest
  #   restart: always
  #   environment:
  #     TZ: "America/Los_Angeles"
  #     PUID: "1001"
  #     PGID: "0"
  #     BRAINZCODE: "rhkBPis5TolxbzQzJtOnWcEgQLC1EQMOo8vbYRC3"
  #     WEBADDRESS: "172.21.0.3"
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - "${LAB_STORAGE:?err}/config/musicbrainz:/config"
  #     - "${LAB_STORAGE:?err}/plex/music:/data"
  #     - "/etc/localtime:/etc/localtime:ro"
  # lazylibrarian:
  #   depends_on:
  #     - sabnzbd
  #   image: linuxserver/lazylibrarian:latest
  #   restart: always
  #   environment:
  #     TZ: "America/Los_Angeles"
  #     PUID: "1001"
  #     PGID: "0"
  #   ports:
  #     - "5299:5299"
  #   volumes:
  #     - "${LAB_STORAGE:?err}/config/lazylibrarian:/config"
  #     - "${LAB_STORAGE:?err}/download/sabnzbd/complete:/downloads"
  #     - "${LAB_STORAGE:?err}/plex/books:/books"
