version: "3"
services:
  appd:
    restart: unless-stopped
    depends_on:
      - hass
    image: acockburn/appdaemon:latest
    environment:
      TZ: "${LAB_TZ:-America/Los_Angeles}"
    ports:
      - "5050:5050"
    volumes:
      - "${CONFIG_STORAGE:?err}/homeassistant:/conf"
      - "/etc/localtime:/etc/localtime:ro"

        #  embyt:
        #    image: emby/embyserver:latest
        #    restart: unless-stopped
        #    environment:
        #      TZ: "${LAB_TZ:-America/Los_Angeles}"
        #      PUID: "1000"
        #      PGID: "0"
        #      VERSION: latest
        #    ports:
        #      - "8096:8096/tcp"
        #    volumes:
        #      - "${LAB_STORAGE:?err}/config/embyt:/config"
        #      - "${LAB_STORAGE:?err}/download/misc/tob:/mnt/share1"

  hass:
    image: homeassistant/home-assistant:latest
    restart: unless-stopped
    network_mode: "host"
    # ports:
    #   - "8123:8123"
    environment:
      TZ: "${LAB_TZ:-America/Los_Angeles}"
      PUID: "1000"
      PGID: "1000"
    volumes:
      - "${CONFIG_STORAGE:?err}/homeassistant:/config"
      - "/etc/localtime:/etc/localtime:ro"

        #  nextcloud:
        #    image: linuxserver/nextcloud
        #    restart: unless-stopped
        #    environment:
        #      TZ: "${LAB_TZ:-America/Los_Angeles}"
        #      PUID: "1000"
        #      PGID: "1000" 
        #    volumes:
        #      - "${LAB_STORAGE:?err}/nextcloud/config:/config"
        #      - "${LAB_STORAGE:?err}/nextcloud/data:/data"
        #    ports:
        #      - "443:443"

  lidarr:
    depends_on:
      - sabnzbd
    image: linuxserver/lidarr:latest
    restart: unless-stopped
    environment:
      TZ: "${LAB_TZ:-America/Los_Angeles}"
      PUID: "1000"
      PGID: "1000"
    ports:
      - "8686:8686"
    volumes:
      - "${CONFIG_STORAGE:?err}/lidarr:/config"
      - "${LAB_STORAGE:?err}/plex/music:/music"
      - "${LAB_STORAGE:?err}/download/sabnzbd/complete:/downloads"

  openvpn:
    image: kylemanna/openvpn:latest
    restart: unless-stopped
    ports:
      - "1194:1194/udp"
    environment:
      TZ: "${LAB_TZ:-America/Los_Angeles}"
    cap_add:
      - "NET_ADMIN"
    volumes:
      - "${CONFIG_STORAGE:?err}/openvpn:/etc/openvpn"
        #    deploy:
        #      placement:
        #        constraints: [node.role == manager]

        #  pihole:
        #    image: pihole/pihole:latest
        #    ports:
        #      - "53:53/tcp"
        #      - "53:53/udp"
        #      - "67:67/udp"
        #      - "80:80/tcp"
        #      - "443:443/tcp"
        #    restart: unless-stopped
        #    environment:
        #      ServerIP: "${LAB_PUBLIC_IP:?err}"
        #      TZ: "${LAB_TZ:-America/Los_Angeles}"
        #      WEBPASSWORD: "${PH_PASS}"
        #      VIRTUAL_HOST: "${HOSTNAME}"
        #      PUID: "1000"
        #      PGID: "0"
        #    volumes:
        #      - "${CONFIG_STORAGE:?err}/pihole:/etc/pihole"
        #      - "${CONFIG_STORAGE:?err}/pihole/pihole_dnsmasq:/etc/dnsmasq.d"
        #
  plex:
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      TZ: "${LAB_TZ:-America/Los_Angeles}"
      PUID: "1000"
      PLEX_UID: "1000"
      PGID: "1000"
      PLEX_GID: "1000"
      VERSION: latest
      PLEX_CLAIM: ${PLEX_CLAIM_ID}
      ADVERTISE_IP: http://${LOCAL_IP}:32400
    network_mode: "host"
    # ports:
    #   - "32400:32400"
    #   - "32400:32400/udp"
    #   - "32469:32469"
    #   - "32469:32469/udp"
    #   - "5353:5353/udp"
    #   - "1900:1900/udp"
    volumes:
      - "${CONFIG_STORAGE:?err}/plex:/config/"
      - "${LAB_STORAGE:?err}/plex/:/data/"
 
  radarr:
    depends_on:
      - sabnzbd
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      TZ: "${LAB_TZ:-America/Los_Angeles}"
      PUID: "1000"
      PGID: "1000"
    ports:
      - "7878:7878"
    volumes:
      - "${CONFIG_STORAGE:?err}/radarr:/config"
      - "${LAB_STORAGE:?err}/plex/movies:/movies"
      - "${LAB_STORAGE:?err}/download/sabnzbd/complete/movies:/downloads"

  sabnzbd:
    image: linuxserver/sabnzbd:latest
    restart: unless-stopped
    environment:
      TZ: "${LAB_TZ:-America/Los_Angeles}"
      PUID: "1000"
      PGID: "1000"
    ports:
      - "8081:8080"
      - "9090:9090"
    volumes:
      - "${CONFIG_STORAGE:?err}/sabnzbd:/config"
      - "${LAB_STORAGE:?err}/download/sabnzbd/complete:/downloads"
      - "${LAB_STORAGE:?err}/download/sabnzbd/downloading:/incomplete-downloads"

  sonarr:
    depends_on:
      - sabnzbd
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      TZ: "${LAB_TZ:-America/Los_Angeles}"
      PUID: "1000"
      PGID: "1000"
    ports:
      - "8989:8989"
    volumes:
      - "${CONFIG_STORAGE:?err}/sonarr:/config"
      - "${LAB_STORAGE:?err}/plex/tv:/tv"
      - "${LAB_STORAGE:?err}/download/sabnzbd/complete:/downloads"
